---
title: "binary_outcome_test"
author: "Misbath Daouda"
date: "3/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(magrittr)
library(pastecs)
library(psych)
library(readxl)
```

### Demographics 
```{r, eval = FALSE}
demo <- read_csv("./school_data/demographics.csv") %>% 
  janitor::clean_names() %>% 
  filter(year == "2016-17") %>% 
  mutate(school_year = year) %>% 
  select(-year) %>%
  mutate(school_name = toupper(school_name)) %>%
  drop_na(school_name)

cols = c(19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 38)
demo[,cols] %<>% lapply(function(x) parse_number(x))

```

### Lead data
```{r, eval = FALSE}
lead <- read_csv("./school_data/2017_water_lead.csv") %>% 
  janitor::clean_names() %>% 
  mutate(number_of_elevated_samples = as.numeric(number_of_elevated_samples),
         number_of_samples_tested = as.numeric(number_of_samples_tested),
         percent_elevated = 
           round((number_of_elevated_samples / number_of_samples_tested)*100, 2),
         geographical_district = as.character(geographical_district)) %>% 
#Adding leading 0 for district numbers while always having 2 digits 
  mutate(geographical_district = 
           str_pad(geographical_district, width=2, side="left", pad="0")) %>% 
  mutate(dbn = str_c(geographical_district, building_code)) %>% 
  drop_na(elevated_result)

```

### Scores 
```{r, eval = FALSE}
ela_scores <- read_csv("./school_data/ela_scores.csv") %>% 
  janitor::clean_names() %>% 
  filter(year %in% c("2016", "2017")) %>% 
  arrange(dbn, year) %>% 
  rename(mean_ela_score = "mean_scale_score", number_tested_ela = "number_tested") %>% 
  select(dbn:mean_ela_score)

math_scores <- read_csv("./school_data/math_scores.csv") %>% 
  janitor::clean_names() %>% 
  filter(year %in% c("2016", "2017")) %>%
  arrange(dbn, year) %>%
  rename(mean_math_score = "mean_scale_score", number_tested_math = "number_tested") %>% 
  select(dbn:mean_math_score)

ela_math <- full_join(math_scores, ela_scores) %>% 
  mutate(mean_ela_score = as.numeric(mean_ela_score),
         mean_math_score = as.numeric(mean_math_score)) %>%
  filter(grade == "All Grades") 

```

### Adding proper building codes 
```{r, eval = FALSE}
building_codes <- read_excel("./school_data/2017_water_lead.xlsx", sheet = "Building School Key", skip = 1) %>%
  janitor::clean_names() %>%
  mutate(school_name = toupper(school_name)) 

codes_scores <- left_join(ela_math, building_codes, by = "school_name") %>% 
  rename(school_name_scores = school_name)

codes_demo <- left_join(demo, building_codes, by = "school_name")

```

### Merging
```{r, eval = FALSE}
codes_demo_lead <- left_join(lead, codes_demo, by = "building_code") %>% 
  rename(school_name_lead = school_name)

codes_demo_lead_scores <- left_join(codes_demo_lead, codes_scores, by = "building_code")%>% 
  filter(school_name_lead == school_name_scores) %>% 
  group_by(year, school_name_scores) %>% 
  mutate(elevated_result = recode(elevated_result, "Yes" = "1", "No" = "0")) %>%
  mutate(elevated_result = as.numeric(elevated_result)) %>%
  summarize(elevated_result = sum(elevated_result),
            math_score = mean(mean_math_score),
            ela_score = mean(mean_ela_score)) %>% 
  mutate(elevated_result = recode(elevated_result, "2" = "1", "3" = "1", "4" = "1",
                                  "5" = "1", "8" = "1", "0" = "0", "1" = "1")) %>%
  ungroup() %>% rename(school_name=school_name_scores)

final_binary_data <- codes_demo_lead_scores %>% left_join(demo, by = "school_name") %>% drop_na()

#write_csv(final_binary_data, "./final_binary_data.csv")
```

### Model with binary lead outcome (2016)
```{r}
final_binary_data = read_csv("./final_binary_data.csv")
data_2016 = final_binary_data %>% filter(year == "2016") 

model_dem = glm(elevated_result ~ percent_white+percent_asian+percent_black+percent_hispanic+economic_need_index+percent_english_language_learners, family = "binomial", data = data_2016)

model_dem_table = broom::tidy(model_dem) %>%
  mutate_if(is.numeric, round, 2)

model_math <- lm(math_score ~ elevated_result+percent_white+percent_asian+percent_black+percent_hispanic+economic_need_index+percent_english_language_learners,data = data_2016)

model_math_table = broom::tidy(model_math) %>%
  mutate_if(is.numeric, round, 2)

model_ela <- lm(ela_score ~ elevated_result+percent_white+percent_asian+percent_black+percent_hispanic+economic_need_index+percent_english_language_learners,data = data_2016)

model_ela_table = broom::tidy(model_ela) %>%
  mutate_if(is.numeric, round, 2)

knitr::kable(model_dem_table)
knitr::kable(model_math_table)
knitr::kable(model_ela_table)

```

