---
title: ""
author: "Brennan Baker"
date: "February 26, 2020"
output: html_document
---

```{r setup, include = FALSE, message=FALSE}
#install.packages("psych")
library(tidyverse)
library(magrittr)
library(pastecs)
library(psych)
library(readxl)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

# Misbath: A note on merging
# My understanding is that the DBN associated with each school is made up of 3 elements
# - the geographical district number (2 digits)
# - the borough code (a capital letter, ie K is for Brooklyn)
# - the school/building number (3 digits)

```

### Demographics
```{r, message=FALSE}
demo <- read_csv("./school_data/demographics.csv") %>% 
  janitor::clean_names() %>% 
  filter(year == "2016-17") %>% 
  mutate(school_year = year) %>% 
  select(-year) %>%
  mutate(school_name = toupper(school_name)) %>%
  drop_na(school_name)

#Removing the % sign from "percent_" columns for future analyses 
cols = c(19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 38)
demo[,cols] %<>% lapply(function(x) parse_number(x))

#The Economic Need Index (ENI) estimates the percentage of students facing economic hardship
#I also removed the % sign from that column, but need to keep in mind that it's a percentage 

#names(demo)
#str(demo)
#view(demo)

```

### Lead data
```{r, message=FALSE}
lead <- read_csv("./school_data/2017_water_lead.csv") %>% 
  janitor::clean_names() %>% 
  mutate(number_of_elevated_samples = as.numeric(number_of_elevated_samples),
         number_of_samples_tested = as.numeric(number_of_samples_tested),
         percent_elevated = 
           round((number_of_elevated_samples / number_of_samples_tested)*100, 2),
         geographical_district = as.character(geographical_district)) %>% 
#Adding leading 0 for district numbers while always having 2 digits 
  mutate(geographical_district = 
           str_pad(geographical_district, width=2, side="left", pad="0")) %>% 
  mutate(dbn = str_c(geographical_district, building_code)) %>% 
  drop_na(elevated_result) 
  
#summary(lead)
#names(lead)
#str(lead)
#view(lead)

```


### Scores
```{r, message=FALSE}
ela_scores <- read_csv("./school_data/ela_scores.csv") %>% 
  janitor::clean_names() %>% 
  filter(year %in% c("2016", "2017")) %>% 
  arrange(dbn, year) %>% 
  rename(mean_ela_score = "mean_scale_score", number_tested_ela = "number_tested") %>% 
  select(dbn:mean_ela_score)

#names(ela_scores)
#str(ela_scores)
#view(ela_scores)

math_scores <- read_csv("./school_data/math_scores.csv") %>% 
  janitor::clean_names() %>% 
  filter(year %in% c("2016", "2017")) %>%
  arrange(dbn, year) %>%
  rename(mean_math_score = "mean_scale_score", number_tested_math = "number_tested") %>% 
  select(dbn:mean_math_score)

#names(math_scores)
#str(math_scores)
#view(math_scores)

```

#adds building codes to math, ela and demo datasets
```{r, message=FALSE}
building_codes <- read_excel("./school_data/2017_water_lead.xlsx", sheet = "Building School Key", skip = 1) %>%
  janitor::clean_names() %>%
  mutate(school_name = toupper(school_name)) 


#view(building_codes)
#view(ela_scores)

ela_math <- full_join(math_scores, ela_scores) %>% 
  mutate(mean_ela_score = as.numeric(mean_ela_score),
         mean_math_score = as.numeric(mean_math_score)) %>%
  filter(grade == "All Grades") 

#view(ela_math)

codes_scores <- left_join(ela_math, building_codes, by = "school_name") %>% 
  rename(school_name_scores = school_name)
#view(codes_ela_scores)

codes_demo <- left_join(demo, building_codes, by = "school_name")
#view(codes_demo)
```

#merging files based on building code
```{r}
codes_demo_lead <- left_join(lead, codes_demo, by = "building_code") %>% 
  rename(school_name_lead = school_name)
#Adding lead data doubles our observations - something is wrong here. we have more schools tested for lead than tested for scores. E.g. buulding X has 2 schools in it, so 2 schools are assigned the lead data from testing that building. But only 1 school in the building was tested for math and ela. We needd to remove the school that was not tester by filtering so that school_name_scores == school_name_lead - the school name from the lead dataset equals the school name from the testing dataset.

summary(codes_demo_lead)

#in some cases one school goes across multiple buildings. Summarized lead testing for each school.
codes_demo_lead_scores <- left_join(codes_demo_lead, codes_scores, by = "building_code")%>% filter(school_name_lead == school_name_scores) %>% group_by(year, school_name_scores) %>% 
  summarize(number_of_samples_tested = sum(number_of_samples_tested),
            number_of_elevated_samples = sum(number_of_elevated_samples),
            math_score = mean(mean_math_score),
            ela_score = mean(mean_ela_score)) %>% 
  mutate(percent_elevated = number_of_elevated_samples/number_of_samples_tested) %>% 
  ungroup() %>% rename(school_name=school_name_scores) 


final_data <- codes_demo_lead_scores %>% left_join(demo, by = "school_name") %>% drop_na()

#numebrs make sense now - we have 2177 data points for test scores, and 2064 data points in our final data set. 
```

###2017 models
```{r}
data_2017 = final_data %>% filter(year == "2017") 
#NoteL glm with link=logit when the outcome is a proportion. Properties of logit - bound between 0 and 1! I also read that it is ok for the predictor variables to be a proportion in linear models, but we should ask Marianthi just in case.  


#ses model - no significant ses predictors of elevated lead
model <- glm(percent_elevated ~ percent_white+percent_asian+percent_black+percent_hispanic+economic_need_index+percent_english_language_learners, family=binomial("logit"),data = data_2017)
broom::tidy(model) %>%
  mutate_if(is.numeric, round, 2)

#scores models
#elevated lead predicts math scores but not ela scores, controlling for ses. Economic need index and percent english language learners are also strong predictors of both scores.
model <- lm(math_score ~ percent_elevated+percent_white+percent_asian+percent_black+percent_hispanic+economic_need_index+percent_english_language_learners,data = data_2017)
broom::tidy(model) %>%
  mutate_if(is.numeric, round, 2)


model <- lm(ela_score ~ percent_elevated+percent_white+percent_asian+percent_black+percent_hispanic+economic_need_index+percent_english_language_learners,data = data_2017)
broom::tidy(model) %>%
  mutate_if(is.numeric, round, 2)
```

###2016 models. Here lead predicts math and ela scores.
```{r}
data_2016 = final_data %>% filter(year == "2016") 
#NoteL glm with link=logit when the outcome is a proportion. Properties of logit - bound between 0 and 1! I also read that it is ok for the predictor variables to be a proportion in linear models, but we should ask Marianthi just in case.  



model <- glm(percent_elevated ~ percent_white+percent_asian+percent_black+percent_hispanic+economic_need_index+percent_english_language_learners, family=binomial("logit"),data = data_2016)
broom::tidy(model) %>%
  mutate_if(is.numeric, round, 2)


model <- lm(math_score ~ percent_elevated+percent_white+percent_asian+percent_black+percent_hispanic+economic_need_index+percent_english_language_learners,data = data_2016)
broom::tidy(model) %>%
  mutate_if(is.numeric, round, 2)


model <- lm(ela_score ~ percent_elevated+percent_white+percent_asian+percent_black+percent_hispanic+economic_need_index+percent_english_language_learners,data = data_2016)
broom::tidy(model) %>%
  mutate_if(is.numeric, round, 2)
```



### Merged files (OLD)
```{r OLD merging code, eval=FALSE}
demo_lead <- left_join(lead, demo, by = "dbn") %>%
  drop_na() %>% 
  select(-building_name, -building_address)

#once we match the demographics dataset to the lead results, the sample size decreases from 1544 (N of lead results) to 828 

ela_math <- merge(math_scores, ela_scores) %>% 
  arrange(year, dbn) %>% 
  filter(grade == "All Grades") %>% 
  mutate(mean_ela_score = as.numeric(mean_ela_score),
         mean_math_score = as.numeric(mean_math_score)) %>% 
  select(-school_name)

#I filtered the test scores to only include "all grades" but we also have data for grades 3, 4, and 5 individually 

ela_math_2016 <- ela_math %>% 
  filter(year == "2016")

ela_math_2017 <- ela_math %>% 
  filter(year == "2017")

demo_lead_scores_2016 <- left_join(demo_lead, ela_math_2016, by = "dbn") %>% 
  drop_na()

demo_lead_scores_2017 <- left_join(demo_lead, ela_math_2017, by = "dbn") %>% 
  drop_na()

```

### Descriptive stats  
```{r, eval=FALSE}
#Lead stats
view(data_2016)

lead_results <- data_2016 %>%
                select(number_of_samples_tested, number_of_elevated_samples, percent_elevated)

describe(lead_results) %>% 
  knitr::kable(digits = 2)

skimr::skim(lead_results) 

#Demographics stats 

demo_trends <- final_data %>% 
                select(starts_with("percent"), economic_need_index)

describe(demo_trends) %>% 
  select(n, mean, sd, median, min, max) %>%
  knitr::kable(digits = 2)

skimr::skim(demo_trends)

#Scores stats

ela_math_results <- codes_demo_lead_scores %>%
  filter(year == "2016") %>%
                    select(number_tested_math, number_tested_ela, mean_math_score, mean_ela_score)

describe(ela_math_results) %>% 
  knitr::kable(digits = 2)

skimr::skim(ela_math_results)

```

### Visualization of distributions 
```{r, eval = FALSE}
 final_data %>% 
  ggplot(aes(x = math_score)) + 
  geom_histogram(binwidth = 5, color = "#404788FF", fill = "#404788FF", alpha=.2) + 
  labs(x = "Mean Math Score", y = "Count", title = "Mean Math Score 2016-2017")

 final_data %>% 
  ggplot(aes(x = ela_score)) + 
  geom_histogram(binwidth = 5, color = "#238A8DFF", fill = "#238A8DFF", alpha=.2) + 
  labs(x = "Mean ELA Score", y = "Count", title = "Mean ELA Score 2016-2017")
 
final_data %>%
  ggplot(aes(x = number_of_elevated_samples)) + 
  geom_histogram(binwidth = 2, color = "#DCE319FF", fill = "#DCE319FF", alpha=.2) + 
  labs(x = "Number of Samples with Elevated Lead", y = "Count", title = "Tested Samples with Elevated Lead 2016-2017")
 
```


```{r vizualizing distributions with boxplot, eval = FALSE}

codes_demo_lead_scores %>%
  filter(year == "2016") %>%
  group_by(math_score) %>%
  summarize(n = n()) %>%
  ggplot(aes(x = math_score, y = n)) + 
  geom_boxplot(binwidth = 5, color = "#404788FF", fill = "#404788FF", alpha=.2) + 
  labs(x = "Mean Math Score", y = "Count")

codes_demo_lead_scores %>%
  filter(year == "2016") %>%
  group_by(ela_score) %>%
  summarize(n = n()) %>%
  ggplot(aes(x = ela_score, y = n)) + 
  geom_boxplot(binwidth = 5, color = "#238A8DFF", fill = "#238A8DFF", alpha=.2) + 
  labs(x = "Mean ELA Score", y = "Count")

final_data %>% 
  group_by(number_of_elevated_samples) %>%
  summarize(n = n()) %>%
  ggplot(aes(x = number_of_elevated_samples, y = n)) + 
  geom_boxplot(binwidth = 2, color = "#DCE319FF", fill = "#DCE319FF", alpha=.2) + 
  labs(x = "Percent of Tested Samples with Elevated Lead", y = "Count")

```


### Visualization of relationships 
#did this work? can't get it to run - MS
```{r, eval=FALSE}

#Demographics & lead 

dem_lead = codes_demo_lead_scores %>%
  filter(year == "2016") %>%
  select(starts_with("percent"), elevated_result, -percent_elevated) %>% 
  pivot_longer(
    cols = starts_with("percent_"),
    names_to = "demographics",
    names_prefix = "percent_",
    values_to = "school_percentage") %>%
  group_by(elevated_result, demographics) %>% 
  summarise(average_percentage = mean(school_percentage)) 
  
ggplot(dem_lead, aes(fill=demographics, y=average_percentage, x=elevated_result)) + 
    geom_bar(position="dodge", stat="identity") + 
    labs(x = "Elevated Lead Result", y = "Demographic Breakdown (%)") + 
    theme(legend.position="right")


#ggplot(data, aes(fill=elevated_result, y=average_percentage, #x=demographics)) + 
    #geom_bar(position="dodge", stat="identity") + 
    #labs(x = "Demographics(%)", y = "Elevated Lead Result")


#Demographics & test scores 

dem_scores = codes_demo_lead_scores %>%
  filter(year == "2016") %>%
  select(starts_with("percent"), mean_math_score, mean_ela_score, -percent_elevated) %>%
  pivot_longer(
    cols = starts_with("mean_"),
    names_to = "subject",
    names_prefix = "mean_",
    values_to = "mean_score")

ggplot(dem_scores, aes(y = mean_score)) + 
  #geom_point(aes(x=percent_white, color="% White")) + 
  geom_smooth(method = "lm", aes(x=percent_white, color="% White")) +
  #geom_point(aes(x=percent_black, color="% Black")) + 
  geom_smooth(method = "lm", aes(x=percent_black, color="% Black")) + 
  #geom_point(aes(x=percent_poverty, color="% Poverty")) + 
  geom_smooth(method = "lm", aes(x=percent_poverty, color="% Poverty")) + 
  facet_grid(~subject) + 
  labs(x = "Demographics (%)", y = "Mean Score")

#Lead & test scores 

lead_scores = codes_demo_lead_scores %>%
  filter(year == "2016") %>%
  select(mean_math_score, mean_ela_score, elevated_result, 
         percent_elevated, borough) %>% 
   pivot_longer(
    cols = starts_with("mean_"),
    names_to = "subject",
    names_prefix = "mean_",
    values_to = "mean_score")

lead_scores %>% 
 ggplot(aes(y = mean_score)) + 
  geom_point(aes(x=percent_elevated, color="% Elevated")) + 
  geom_smooth(method = "lm", aes(x=percent_elevated, color="% Elevated")) + 
  facet_grid(~subject)

lead_scores %>% 
  group_by(elevated_result, mean_score) %>% 
  ggplot(aes(fill=subject, y=mean_score, x=elevated_result)) + 
    geom_bar(position="dodge", stat="identity") + 
    labs(x = "Elevated Lead Result", y = "Mean Score") + 
  facet_grid(~borough)

```

#non-linearity
```{r}
library(mgcv)
library(splines)
gam2 <- gam(math_score ~ s(percent_elevated) + percent_white+percent_asian + percent_black + percent_hispanic + economic_need_index + percent_english_language_learners ,data = data_2016)
summary(gam1)
plot(gam1)
#its linear! edf = 1
gam2 <- gam(ela_score ~ s(percent_elevated) + percent_white+percent_asian + percent_black + percent_hispanic + economic_need_index + percent_english_language_learners ,data = data_2016)
summary(gam2)
plot(gam2)
# edf = 4.575. too wiggly, try natural spline
mod.ns.2 <- gam(ela_score ~ ns(percent_elevated,df=2) + percent_white+percent_asian + percent_black + percent_hispanic + economic_need_index + percent_english_language_learners ,data = data_2016)

mod.ns.3 <- gam(ela_score ~ ns(percent_elevated,df=3) + percent_white+percent_asian + percent_black + percent_hispanic + economic_need_index + percent_english_language_learners ,data = data_2016)

mod.ns.4 <- gam(ela_score ~ ns(percent_elevated,df=4) + percent_white+percent_asian + percent_black + percent_hispanic + economic_need_index + percent_english_language_learners ,data = data_2016)

aic.mod.ns.2 <- AIC(mod.ns.2)
aic.mod.ns.3 <- AIC(mod.ns.3)
aic.mod.ns.4 <- AIC(mod.ns.4)
#lowest AIC for 2 df
summary(mod.ns.2)
plot(mod.ns.2)
```

natural spline df=2 plot
```{r}
predscore.ns.2 <- predict(mod.ns.2, se.fit = TRUE, type = "terms" )

# 4c.ii Convert to dataframe 

predscore.ns.2 <- as.data.frame(predscore.ns.2)

# 4c.iii Rename predictions and standard errors
# column has different names since it is one term 

predscore.ns.2 <- predscore.ns.2 %>% 
  mutate( pred = fit.ns.percent_elevated..df...2.,
          se = se.fit.ns.percent_elevated..df...2.)

# 4c.iv Compute 95% confidence intervals 

predscore.ns.2 <- predscore.ns.2 %>% 
  mutate( lci = pred - 1.96*se,
          uci = pred + 1.96*se)

# 4c.v Keep only variables we need

predscore.ns.2 <- predscore.ns.2 %>% select(pred, se, lci, uci)

# 4c.vi Combine with data 

predscore.ns.2 <- predscore.ns.2 %>% bind_cols(data_2016)

# 4c.vii Uncenter data 

predscore.ns.2 <- predscore.ns.2 %>% mutate(predscore = pred + mean(ela_score),
                                        lciscore = lci + mean(ela_score),
                                        uciscore = uci + mean(ela_score))
# 4c.viii Plot

ggplot(predscore.ns.2, aes(percent_elevated)) + 
  geom_line(aes(y = predscore)) + 
  geom_line(aes(y = lciscore), color = "darkgrey") + 
  geom_line(aes(y = uciscore), color = "darkgrey") + 
  geom_rug()
  xlab("Percent elevated lead taps") + 
  ylab("Predicted ELA score") + 
  theme(axis.text = element_text(size = 15)) + 
  theme(axis.title = element_text(size = 20))

#ggsave("natural spline df2 2016 ela score rug.jpg")
```

